### ISSUE TITLE
Instruction in README

### ISSUE THREAD

**Issue by plumest** [jittaearn/django-polls#1]
- Can't set path
```
$ source venv/bin/activate
source: no such file or directory: venv/bin/activate
```

- Can't migration:
``` 
>>> python3 manage.py migrate
Traceback (most recent call last):
    ...
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.
```

- Can't runserver
```
>>> python3 manage.py runserver
Traceback (most recent call last):
    ...
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.
```
- Requirements do not specific enough.

**Comment by jittaearn** [comment]
@plumest 

- Regarding to the issue "Can't set path", I have fixed the instruction in the file README.md and you should be able to run the next command without having to set the path.   

- Under "Can't migration" and "Can't run server", I have fixed the problem. Please try running it again. If any issue occurs please inform me below. Otherwise, please leave a comment if everything works fine.   

Thank you.

**Comment by plumest** [comment]
Everything seems good now. But I think your requirements should be ```Python 3.6.6``` or newer and add-on modules in ```requirements.txt``` are enough, Django already has in a requirement file so it not necessary to show here.   
<img width="408" alt="Screen Shot 2562-09-25 at 22 42 32" src="https://user-images.githubusercontent.com/43769083/65616771-cf4dd480-dfe5-11e9-8ec8-60cbdff82bea.png">

**Comment by jittaearn** [comment]
@plumest 

I have made the requirement in the README.md file more specific and delete the requirement on Django 2.1.2 according to your suggestion. Please recheck the README.md file. If there is any other issue please inform me.   

Thank you.

**Comment by plumest** [comment]
OK
